name = spawn_command
title = Spawn Command
description = Adds a /spawn command that teleports you to the server spawn command.
depends = default
optional_depends = cursed_world
min_minetest_version = 0.4.16
